export const apiPaths = {
  banner: '/layDanhSachBanner',
  youtubePost: '/layDanhSachYT',
  mainCategory: '/layDanhMuc',
  subCategories: '/layDanhMucNho',
  subCategory: '/chiTietDanhMucNho',
  menu: '/menu',
  product: '/layDanhSachSanPham',
  productIncludeSubCategories: '/laySanPhamTheoDanhMucNho',
  productDetail: '/layChiTietSanPham',
  productPagination: '/laySanPhamPhanTrang',
  news: '/layTinTucPhanTrang',
  newsDetail: "/chiTietTinTuc",
  paymentInfo: '/layDanhSachThanhToan',
  orderProduct: '/themDonHang',
  footer: "/footers",
  productWithSubCategory: "/laySanPhamTheoDanhMucNho",
  about: "/layNoiDungGioiThieu",
};
