import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import clsx from 'clsx';
import { MainHeader, TopHeader } from '@/components/global';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Nong Co Hai Tra Tan',
  description: 'Generated by create next app',
};


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const response = await fetch('http://localhost:3000/api/menu', {
    next: { revalidate: 5 },
  });
  const data = await response.json();

  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={clsx(inter.className, 'relative')}
      >
        <header>
          <TopHeader />
          <MainHeader menuData={data.menuData} categoriesData={data.categoriesData} />
        </header>
        <div>{children}</div>
      </body>
    </html>
  );
}
